// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectRelationalMapping.Shared.Database;

namespace MSS.Persistence.ObjectRelationalMapping.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201028163228_addedAvatarSessionMinutesAndDescriptionToAccount")]
    partial class addedAvatarSessionMinutesAndDescriptionToAccount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSS.Domain.Concrete.DatabaseEntities.Credit.Credit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDateUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreditCategoryFK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HTMLDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTMLGotFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTMLMadeBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDateUTC")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("CreditCategoryId");

                    b.ToTable("Credits");

                    b.HasData(
                        new
                        {
                            Id = "c0719349-3072-48bc-8b68-a44e20879456",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditCategoryFK = "452c9c48-2535-460f-af33-df8292dd13d2",
                            HTMLDescription = "<p>Some tasks while creating an UI are repetative. Syncfusion helps by providing components for repetative use.</p>",
                            HTMLGotFrom = "Got from: <a href='https://www.syncfusion.com/products/communitylicense'>Syncfusion community license</a>",
                            HTMLMadeBy = "Made by: <a href='https://www.syncfusion.com/blazor-components'>Syncfusion website</a>",
                            LinkToImage = "https://cdn.syncfusion.com/content/images/Logo/Logo_150dpi.png",
                            SubTitle = "Easy to use premade Blazor components",
                            Title = "Syncfusion"
                        },
                        new
                        {
                            Id = "8b271d71-2c29-42a6-9e08-0248a1d6dde5",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditCategoryFK = "3a76466f-24f4-4abc-bf20-3b4d04f5ab6a",
                            HTMLDescription = "<p>Most, if not all icons came from this provider. This font came with the project when it was created. I kept it for its ease of use.</p>",
                            HTMLGotFrom = "<a href='https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor'>Blazor WebAssembly project builder</a>",
                            HTMLMadeBy = "<a href='https://useiconic.com/open'>Open-Iconic</a>",
                            LinkToImage = "https://img.stackshare.io/service/3029/iconic.png",
                            SubTitle = "Provider of fonts and icons",
                            Title = "Open Iconic"
                        },
                        new
                        {
                            Id = "082a64c1-712b-4f96-8ff9-46eca9e9baeb",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditCategoryFK = "3a76466f-24f4-4abc-bf20-3b4d04f5ab6a",
                            HTMLDescription = "<p>Tim Corey provides many educational video's and tutorials about programming. His content is focused on C# but he covers other languages too. His goal is to make learning C# easier. Awesome guy.</p>",
                            HTMLGotFrom = "Searching for tutorial video's on <a href='https://www.youtube.com'>YouTube</a> about C#",
                            HTMLMadeBy = "<a href='https://www.youtube.com/timcorey'>Tim Corey's YouTube channel</a>",
                            LinkToImage = "https://avatars3.githubusercontent.com/u/1839873?s=400&v=4",
                            SubTitle = "Youtuber with the best C# tuturials",
                            Title = "Tim Corey"
                        },
                        new
                        {
                            Id = "144dd825-c8ca-4344-82e4-ef2c291e5a89",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreditCategoryFK = "3a76466f-24f4-4abc-bf20-3b4d04f5ab6a",
                            HTMLDescription = "<p>Pluralsight has helped me better understand software architecture and desighn patterns. The video's are very thorough and helpfull. One thing is that there is so much info that sometimes it takes long to find something specific.</p>",
                            HTMLGotFrom = "ITvitae giving me an account on <a href='https://www.pluralsight.com/'>Pluralsight</a>",
                            HTMLMadeBy = "<a href='https://www.pluralsight.com/content/pluralsight/en/about/jcr:content/main/generic_block_167843627/parsys/columns/column-parsys-1/executive/parsys/executive_member/gridimage-res.img.75734133-ac30-41ab-8e2a-4b7033ca7e10.jpg'>CEO Aaron Skonnard</a>",
                            LinkToImage = "https://pbs.twimg.com/profile_images/1291779527576653824/vifRmgyc.jpg",
                            SubTitle = "Best educational video streaming service",
                            Title = "Pluralsight"
                        });
                });

            modelBuilder.Entity("MSS.Domain.Concrete.DatabaseEntities.Credit.CreditCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDateUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDateUTC")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("CreditCategories");

                    b.HasData(
                        new
                        {
                            Id = "452c9c48-2535-460f-af33-df8292dd13d2",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubTitle = "Sources that made UI development easier",
                            Title = "Don't reinvent the wheel"
                        },
                        new
                        {
                            Id = "3a76466f-24f4-4abc-bf20-3b4d04f5ab6a",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubTitle = "Sources that helped me gaining knowledge  about programming related subjects",
                            Title = "Food for the brain"
                        });
                });

            modelBuilder.Entity("MSS.Domain.Concrete.DatabaseEntities.UserAccount.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Affix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateUTC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("HTMLDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmitted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModificationDateUTC")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "ffff255c-4499-4cef-92fb-6965e83370f6",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "f199b8ab-7607-4d08-a1c1-56dc3f696b50",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maurice.slegtenhorst@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Maurice",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "Slegtenhorst",
                            LockoutEnabled = true,
                            NormalizedEmail = "MAURICE.SLEGTENHORST@OUTLOOK.COM",
                            NormalizedUserName = "MAURICE.SLEGTENHORST@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "0645377536",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "3feddadf-d954-4264-8c6d-2de27faac393",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "maurice.slegtenhorst@outlook.com"
                        },
                        new
                        {
                            Id = "18636492-975a-4917-a3ee-2b7794672251",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "27884315-9915-4157-9286-7b67a14ce4fe",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mauricesoftwaresolution@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Maurice",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "Slegtenhorst",
                            LockoutEnabled = true,
                            NormalizedEmail = "MAURICESOFTWARESOLUTION@OUTLOOK.COM",
                            NormalizedUserName = "MAURICESOFTWARESOLUTION@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "0645377536",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8fcc2316-1305-481c-ba8d-e83f3850c012",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "mauricesoftwaresolution@outlook.com"
                        },
                        new
                        {
                            Id = "93420010-a0f1-4861-9188-971bc75236c0",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "d53194ca-35e6-4049-96f4-07dd018c3440",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hanneke.slegtenhorst1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Hanneke",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "Slegtenhorst",
                            LockoutEnabled = true,
                            NormalizedEmail = "HANNEKE.SLEGTENHORST1@GMAIL.COM",
                            NormalizedUserName = "HANNEKE.SLEGTENHORST1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "060000210826",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "de7d5489-2776-41f8-82d0-72de2a69052b",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "hanneke.slegtenhorst1@gmail.com"
                        },
                        new
                        {
                            Id = "039b8205-9888-478e-a68d-5dd53030de40",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "f9dd0c8e-12fd-47bb-b9a4-575db7ac3ad3",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "privilegedemployee01@mss.nl",
                            EmailConfirmed = true,
                            FirstName = "PrivilegedEmployee_01",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "None",
                            LockoutEnabled = true,
                            NormalizedEmail = "PRIVILEGEDEMPLOYEE01@MSS.NL",
                            NormalizedUserName = "PRIVILEGEDEMPLOYEE01@MSS.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "060000613018",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "983faa56-fbcc-42b6-ba2c-27b906bafc7b",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "privilegedemployee01@mss.nl"
                        },
                        new
                        {
                            Id = "737ef0f7-2b06-437b-9803-0337cab0087b",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "595f798f-8a62-4b67-9884-c278314987d1",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "employee01@mss.nl",
                            EmailConfirmed = true,
                            FirstName = "Employee_01",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "None",
                            LockoutEnabled = true,
                            NormalizedEmail = "EMPLOYEE01@MSS.NL",
                            NormalizedUserName = "EMPLOYEE01@MSS.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "060000729371",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5d8a93af-f0f4-4b73-b68e-b6475446f814",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "employee01@mss.nl"
                        },
                        new
                        {
                            Id = "4cdceea4-bd1b-4fdd-b7f5-6cdbae25f6bd",
                            AccessFailedCount = 0,
                            AvatarLink = "https://respondsystems.com/wp-content/uploads/2015/12/RSI_generic_avatar-150x150.jpg",
                            ConcurrencyStamp = "f6578eb4-5409-4e3f-8ac4-4b0dbf61ceb1",
                            CreationDateUTC = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "standarduser01@mss.nl",
                            EmailConfirmed = true,
                            FirstName = "StandardUser_01",
                            HTMLDescription = "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci sagittis eu volutpat odio facilisis mauris sit amet. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus. Varius vel pharetra vel turpis nunc eget lorem dolor. Adipiscing elit ut aliquam purus. Enim sed faucibus turpis in eu mi bibendum. Fames ac turpis egestas maecenas pharetra. Sed turpis tincidunt id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing. Quam quisque id diam vel quam elementum pulvinar.</p><p>Eu augue ut lectus arcu bibendum at varius vel pharetra. Sapien faucibus et molestie ac feugiat sed lectus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nunc non blandit massa enim nec dui nunc. Vel pharetra vel turpis nunc eget lorem. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Est ante in nibh mauris cursus mattis molestie. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. In ornare quam viverra orci sagittis eu volutpat. Ultrices sagittis orci a scelerisque purus. Lacus laoreet non curabitur gravida arcu ac. Amet mattis vulputate enim nulla aliquet porttitor lacus. Fermentum posuere urna nec tincidunt praesent semper. Netus et malesuada fames ac turpis egestas maecenas pharetra. Tellus cras adipiscing enim eu turpis egestas.</p>",
                            IsAdmitted = true,
                            LastName = "None",
                            LockoutEnabled = true,
                            NormalizedEmail = "STANDARDUSER01@MSS.NL",
                            NormalizedUserName = "STANDARDUSER01@MSS.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEAYzvSEjXHpeBksADojyfhWipzFSJ2cVxoTKtkNkZpn7Tkl41u16FSpBKOLF0MI8ww==",
                            PhoneNumber = "060000073565",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c4af593e-aecb-44c6-a936-44f574e359fe",
                            SessionTimeMinutes = 10,
                            TwoFactorEnabled = false,
                            UserName = "standarduser01@mss.nl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "f57b1b17-7225-4820-ad10-9bfc0a5ff0ef",
                            ConcurrencyStamp = "f63212df-4bf6-4906-b5ff-1754c1c294e7",
                            Name = "StandardUser",
                            NormalizedName = "STANDARDUSER"
                        },
                        new
                        {
                            Id = "34e49450-a541-419d-8877-b1ebc5e75139",
                            ConcurrencyStamp = "6747ca20-1f08-4f15-98b9-9efaa6b7cb6a",
                            Name = "PrivilegedUser",
                            NormalizedName = "PRIVILEGEDUSER"
                        },
                        new
                        {
                            Id = "c55a5d82-7454-4205-a53a-fa6608723ecb",
                            ConcurrencyStamp = "439d6c4c-bdcb-4077-9c35-da71c387bb49",
                            Name = "Volenteer",
                            NormalizedName = "VOLENTEER"
                        },
                        new
                        {
                            Id = "af9961f5-cd2e-4664-a20c-c5be32cb0125",
                            ConcurrencyStamp = "7cc82936-905c-4fd3-af9a-d8018e0395ec",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "b1369f51-9042-4a57-82d1-ec43f75cd38e",
                            ConcurrencyStamp = "9236505b-0088-445e-be3b-f4066f60f621",
                            Name = "PrivilegedEmployee",
                            NormalizedName = "PRIVILEGEDEMPLOYEE"
                        },
                        new
                        {
                            Id = "8c6f6617-d4ef-4eb7-8d47-9c89fd944f57",
                            ConcurrencyStamp = "a102ed38-3ad9-432c-a435-9cdfbdabf630",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "ffff255c-4499-4cef-92fb-6965e83370f6",
                            RoleId = "8c6f6617-d4ef-4eb7-8d47-9c89fd944f57"
                        },
                        new
                        {
                            UserId = "18636492-975a-4917-a3ee-2b7794672251",
                            RoleId = "8c6f6617-d4ef-4eb7-8d47-9c89fd944f57"
                        },
                        new
                        {
                            UserId = "93420010-a0f1-4861-9188-971bc75236c0",
                            RoleId = "8c6f6617-d4ef-4eb7-8d47-9c89fd944f57"
                        },
                        new
                        {
                            UserId = "039b8205-9888-478e-a68d-5dd53030de40",
                            RoleId = "b1369f51-9042-4a57-82d1-ec43f75cd38e"
                        },
                        new
                        {
                            UserId = "737ef0f7-2b06-437b-9803-0337cab0087b",
                            RoleId = "af9961f5-cd2e-4664-a20c-c5be32cb0125"
                        },
                        new
                        {
                            UserId = "4cdceea4-bd1b-4fdd-b7f5-6cdbae25f6bd",
                            RoleId = "f57b1b17-7225-4820-ad10-9bfc0a5ff0ef"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MSS.Domain.Concrete.DatabaseEntities.Credit.Credit", b =>
                {
                    b.HasOne("MSS.Domain.Concrete.DatabaseEntities.Credit.CreditCategory", "CreditCategory")
                        .WithMany("Credits")
                        .HasForeignKey("CreditCategoryId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MSS.Domain.Concrete.DatabaseEntities.UserAccount.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MSS.Domain.Concrete.DatabaseEntities.UserAccount.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSS.Domain.Concrete.DatabaseEntities.UserAccount.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MSS.Domain.Concrete.DatabaseEntities.UserAccount.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
